from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any
from datetime import datetime
from enum import Enum


class InsightType(str, Enum):
    """Types of coaching insights"""
    STRENGTH = "strength"
    WEAKNESS = "weakness"
    IMPROVEMENT = "improvement"
    WARNING = "warning"
    TIP = "tip"
    PATTERN = "pattern"
    ACHIEVEMENT = "achievement"


class InsightPriority(str, Enum):
    """Priority levels for insights"""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class CoachingInsight(BaseModel):
    """A single coaching insight generated by AI"""
    id: str
    type: InsightType
    priority: InsightPriority
    title: str
    description: str
    evidence: List[str] = Field(default_factory=list, description="Supporting data points")

    # Actionability
    actionable: bool = Field(True, description="Whether this insight has actions")
    recommended_actions: List[str] = Field(default_factory=list)

    # Context
    related_matches: List[str] = Field(default_factory=list, description="Match IDs")
    related_champions: List[str] = Field(default_factory=list)

    # Metadata
    generated_at: str
    confidence_score: float = Field(..., ge=0, le=1)

    class Config:
        json_schema_extra = {
            "example": {
                "id": "insight_vision_improvement",
                "type": "improvement",
                "priority": "high",
                "title": "Your vision score has increased by 35%",
                "description": "Over the last month, your average vision score improved from 28 to 38. This suggests better map awareness and ward placement.",
                "evidence": [
                    "Vision score: 28 → 38 (+35%)",
                    "Wards placed per game: 12 → 16",
                    "Control wards purchased: +2.3 per game"
                ],
                "actionable": True,
                "recommended_actions": [
                    "Continue focusing on early control ward purchases",
                    "Try to maintain 1.5+ vision score per minute"
                ],
                "related_matches": [],
                "related_champions": [],
                "generated_at": "2025-01-15T10:30:00Z",
                "confidence_score": 0.92
            }
        }


class RecommendationCategory(str, Enum):
    """Categories for recommendations"""
    CHAMPION_POOL = "champion_pool"
    ITEMIZATION = "itemization"
    PLAYSTYLE = "playstyle"
    MACRO_STRATEGY = "macro_strategy"
    MECHANICS = "mechanics"
    MENTAL = "mental"


class Recommendation(BaseModel):
    """Actionable recommendation for improvement"""
    id: str
    category: RecommendationCategory
    title: str
    description: str
    difficulty: str = Field(..., description="'easy', 'medium', 'hard'")
    estimated_impact: str = Field(..., description="'low', 'medium', 'high'")

    # Specific steps
    steps: List[str] = Field(default_factory=list)

    # Tracking
    completed: bool = False
    progress: int = Field(0, ge=0, le=100, description="Progress percentage")

    # AI generated
    rationale: str = Field(..., description="Why this recommendation matters")
    expected_outcome: str = Field(..., description="What improvement to expect")

    class Config:
        json_schema_extra = {
            "example": {
                "id": "rec_expand_champion_pool",
                "category": "champion_pool",
                "title": "Expand your champion pool with a tank",
                "description": "Your champion pool lacks a reliable tank option. Adding one would improve team composition flexibility.",
                "difficulty": "medium",
                "estimated_impact": "high",
                "steps": [
                    "Choose a meta tank (Ornn, Sion, or Malphite)",
                    "Play 10 normal games to learn basics",
                    "Watch 2-3 VOD reviews of high-level play",
                    "Integrate into ranked when comfortable"
                ],
                "completed": False,
                "progress": 0,
                "rationale": "In 45% of your recent games, your team lacked a frontline. Having a tank option increases flexibility.",
                "expected_outcome": "Better team composition synergy and +3-5% win rate in tank-favorable metas"
            }
        }


class ChatMessage(BaseModel):
    """A message in the coaching chat"""
    id: str
    role: str = Field(..., description="'user' or 'assistant'")
    content: str
    timestamp: str

    # Rich content
    insights: List[CoachingInsight] = Field(default_factory=list)
    recommendations: List[Recommendation] = Field(default_factory=list)
    match_references: List[str] = Field(default_factory=list)


class CoachingSession(BaseModel):
    """A coaching conversation session"""
    session_id: str
    puuid: str
    started_at: str
    last_updated: str

    # Conversation
    messages: List[ChatMessage] = Field(default_factory=list)

    # Session context
    focus_areas: List[str] = Field(default_factory=list, description="What the player wants to improve")
    analyzed_matches: List[str] = Field(default_factory=list, description="Match IDs analyzed in this session")


class Goal(BaseModel):
    """A player-set goal with AI tracking"""
    id: str
    title: str
    description: str
    category: str  # 'rank', 'champion_mastery', 'stat_improvement', 'custom'

    # Target
    target_value: Optional[float] = None
    target_date: Optional[str] = None

    # Tracking
    current_value: Optional[float] = None
    progress_percentage: int = Field(0, ge=0, le=100)
    status: str = Field(..., description="'in_progress', 'completed', 'abandoned'")

    # AI assistance
    ai_checkpoints: List[str] = Field(default_factory=list, description="AI-suggested checkpoints")
    related_insights: List[str] = Field(default_factory=list, description="Insight IDs")

    created_at: str
    completed_at: Optional[str] = None

    class Config:
        json_schema_extra = {
            "example": {
                "id": "goal_reach_plat",
                "title": "Reach Platinum by end of season",
                "description": "Climb from Gold II to Platinum IV",
                "category": "rank",
                "target_value": None,
                "target_date": "2025-11-01",
                "current_value": None,
                "progress_percentage": 35,
                "status": "in_progress",
                "ai_checkpoints": [
                    "Achieve 55%+ win rate over 20 games",
                    "Master 2 champions to 65%+ win rate",
                    "Improve vision score to 1.5+ per minute"
                ],
                "related_insights": [],
                "created_at": "2025-01-01T00:00:00Z",
                "completed_at": None
            }
        }


class PlayerCoaching(BaseModel):
    """Complete coaching data for a player"""
    puuid: str
    summoner_name: str

    # Active insights
    current_insights: List[CoachingInsight] = Field(default_factory=list)

    # Active recommendations
    active_recommendations: List[Recommendation] = Field(default_factory=list)
    completed_recommendations: List[Recommendation] = Field(default_factory=list)

    # Goals
    active_goals: List[Goal] = Field(default_factory=list)
    completed_goals: List[Goal] = Field(default_factory=list)

    # Session history
    recent_sessions: List[CoachingSession] = Field(default_factory=list)

    # AI personality preferences
    coaching_style: str = Field("balanced", description="'supportive', 'direct', 'analytical', 'balanced'")

    last_updated: str
